services:
  web:
    build: .
    container_name: ${WEB_CONTAINER_NAME}
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ${WEB_VOLUME}:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      interval: 5s
      retries: 3
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 30s

  backup:
    image: alpine
    container_name: ${BACKUP_CONTAINER_NAME}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql:ro
      - ${BACKUP_VOLUME}:/backup
    entrypoint: >
      sh -c "
      apk add --no-cache mariadb-client &&
      mkdir -p /backup &&
      while true; do
        TIMESTAMP=$(date +%F_%H-%M)
        BACKUP_FILE=\"/backup/openxe_${TIMESTAMP}.sql.gz\"

        echo \"[INFO] Starte Backup: \$BACKUP_FILE\"
        mysqldump -h db -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} | gzip > \"\$BACKUP_FILE\"

        if [ \$? -eq 0 ]; then
          echo \"[OK] Backup erfolgreich erstellt.\"
        else
          echo \"[ERROR] Backup fehlgeschlagen!\" >&2
        fi

        echo \"[INFO] Prüfe alte Backups zur Rotation...\"
        ls -1t /backup/openxe_*.sql.gz | tail -n +8 | xargs -r rm --

        echo \"[INFO] Warte 24h bis zum nächsten Backup...\"
        sleep 86400
      done
      "


    depends_on:
      - db

volumes:
  db_data:

